import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ClerkProvider>
                <body
                    className={cn(
                        font.className,
                        "text-gray-500 px-[5%] w-full overflow-x-hidden overflow-y-auto"
                    )}
                >
                    <Navbar />
                    {children}
                    <Footer />
                </body>
            </ClerkProvider>
        </html>
    );
}
